# ----------------------------------------
# HUAWEI SOLAR INPUT - User Specific Input
# ----------------------------------------
# version: 
# branch: alpha-018_map0-support
# domain: https://github.com/JensenNick/huawei_solar_pees
# codeowner: Nick Jensen
#
# This is the optional "Huawei Solar PEES Input package" which is used to save your
# specific solar PV settings for the efficiency corrected power input sensor. This
# package can only be used along with the "Huawei Solar PEES package" and the code
# for the Lovelace card. The package allow you to save your specific solar PV settings
# between updates of the "Huawei Solar PEES package". If you do not use the "Efficiency
# Corrected Input Power Sensor" you do not need to do anything.
#
# You add your specific solar PV settings for the "Efficiency Corrected Input Power
# Sensor" in the Lovelace card. The efficiency corrected input power sensor has been
# implemented in the "Huawei Solar PEES package" so you do not need to copy/paste it
# from the Wiki Pages.
#
# You should only make changes in the Lovelace card, not in the code below. Advanced
# users can adjust the input_numbers, min, "max and step to their liking, but be aware
# of the impact that these input numbers have. Please refer to the Wiki Pages
#
# You still need to edit your input sensors in the huawei_solar_pees.yaml file if your
# input sensors do not match the ones used by default.
#
# -----------
# AUTOMATIONS
# -----------
automation:
  ## ------------------------------
  ## Switch Inverter Between Phases
  - alias: "Switch Inverter #1 to 1phase L1"
    trigger:
      platform: state
      entity_id: input_boolean.inverter_1_1phase_l1
      to: "on"
    action:
      - action: input_boolean.turn_off
        entity_id: input_boolean.inverter_1_3phase_m1
      - action: input_boolean.turn_off
        entity_id: input_boolean.inverter_1_3phase_map0
    mode: single
  - alias: "Switch Inverter #1 to 3phase M1"
    trigger:
      platform: state
      entity_id: input_boolean.inverter_1_3phase_m1
      to: "on"
    action:
      - action: input_boolean.turn_off
        entity_id: input_boolean.inverter_1_1phase_l1
      - action: input_boolean.turn_off
        entity_id: input_boolean.inverter_2_3phase_map0
  - alias: "Switch Inverter #1 to 3phase MAP0"
    trigger:
      platform: state
      entity_id: input_boolean.inverter_1_3phase_map0
      to: "on"
    action:
      - action: input_boolean.turn_off
        entity_id: input_boolean.inverter_1_1phase_l1
      - action: input_boolean.turn_off
        entity_id: input_boolean.inverter_2_3phase_m1
  - alias: "Switch Inverter #2 to 1phase L1"
    trigger:
      platform: state
      entity_id: input_boolean._inverter_2_1phase_l1
      to: "on"
    action:
      - action: input_boolean.turn_off
        entity_id: input_boolean.inverter_2_3phase_m1
      - action: input_boolean.turn_off
        entity_id: input_boolean.inverter_2_3phase_map0
    mode: single
  - alias: "Switch Inverter #2 to 3phase M1"
    trigger:
      platform: state
      entity_id: input_boolean.inverter_2_3phase_m1
      to: "on"
    action:
      - action: input_boolean.turn_off
        entity_id: input_boolean.inverter_2_1phase_l1
      - action: input_boolean.turn_off
        entity_id: input_boolean.inverter_2_3phase_map0
  - alias: "Switch Inverter #2 to 3phase MAP0"
    trigger:
      platform: state
      entity_id: input_boolean.inverter_2_3phase_map0
      to: "on"
    action:
      - action: input_boolean.turn_off
        entity_id: input_boolean.inverter_2_1phase_l1
      - action: input_boolean.turn_off
        entity_id: input_boolean.inverter_2_3phase_m1
# -------------
# INPUT BOOLEAN
# -------------
input_boolean:
  inverter_1_1phase_l1:
    name: "Inverter #1 1phase L1"
  inverter_1_3phase_m1:
    name: "Inverter #1 3phase M1"
  inverter_1_3phase:
    name: "Inverter #1 3phase MAP0"
  inverter_2_1phase_l1:
    name: "Inverter #2 1phase L1"
  inverter_2_3phase_m1:
    name: "Inverter #2 3phase M1"
  inverter_2_3phase:
    name: "Inverter #2 3phase MAP0"
# ------------
# INPUT NUMBER
# ------------
input_number:
  ## --------------------
  ## Inverter #1 Settings
  inverter_1_operating_voltage_l1:
    name: "Inverter #1 Operating Voltage L1"
    min: 90
    max: 560
    step: 5
  inverter_1_operating_voltage_m1:
    name: "Inverter #1 Operating Voltage M1"
    min: 140
    max: 980
    step: 5
  inverter_1_operating_volatge_map0:
    name: "inverter #1 Operating Voltage MAP0"
    min: 160
    max: 1000
    step: 5
  inverter_1_overall_factor:
    name: "Inverter #1 Overall Factor"
    min: 98
    max: 102
    step: 0.2
  ## --------------------
  ## Inverter #2 Settings
  inverter_2_operating_voltage_l1:
    name: "Inverter #2 Operating Voltage L1"
    min: 90
    max: 560
    step: 5
  inverter_2_operating_voltage_m1:
    name: "Inverter #2 Operating Voltage M1"
    min: 140
    max: 980
    step: 5
  inverter_2_operating_volatge_map0:
    name: "inverter #1 Operating Voltage MAP0"
    min: 160
    max: 1000
    step: 5
  inverter_2_overall_factor:
    name: "Inverter #2 Overall Factor"
    min: 98
    max: 102
    step: 0.2
  ## ------------------
  ## Battery Efficiency
  battery_rated_capacity:
    name: "Battery Rated Capacity (in kWh)"
    min: 5
    max: 30
    step: 5
  battery_efficiency_soc_trigger:
    name: "Battery Efficiency SOC Trigger (Recomended Set 50%)"
    min: 0
    max: 100
    step: 5
  battery_efficiency_start_value_charge:
    name: "Battery Efficiency Start Value Charge (in kW)"
    min: 0
    max: 120000
    step: 0.01
    mode: box
  battery_efficiency_start_value_discharge:
    name: "Battery Efficiency Start Value Disharge (in kW)"
    min: 0
    max: 120000
    step: 0.01
    mode: box
  ## Battery Charge Power
  battery_charge_power:
    name: "Battery Charge Power"
    min: 0
    max: 5
    step: 0.01
  ## ------------
  ## Solar Panels
  panels_on_inverter_1:
    name: "Panels on Inverter #1"
    min: 0
    max: 50
    step: 1
    mode: box
  panels_on_inverter_2:
    name: "Panels on Inverter #2"
    min: 0
    max: 50
    step: 1
    mode: box
  panels_rated_wp:
    name: "Panels Rated Wp"
    min: 100
    max: 999
    step: 1
    mode: box
# ------------ 3 phase
# INPUT SELECT
# ------------
input_select:
  # ---------------
  # Inverter Models
  inverter_1_models:
    name: "Inverter #1 Models"
    options:
      - Select
      - SUN2000 X KTL-L1 Models
      - SUN2000 X KTL-M1 Models
      - SUN2000 X KTL-MAP0 Models
  inverter_2_models:
    name: "Inverter #2 Models"
    options:
      - Select
      - SUN2000 X KTL-L1 Models
      - SUN2000 X KTL-M1 Models
      - SUN2000 X KTL-MAP0 Models
  # -----------------
  # Inverter #1 Setup
  inverter_1_1phase_l1_models:
    name: "Inverter #1 1phase L1 Models"
    options:
      - Select
      - SUN2000 2 KTL-L1
      - SUN2000 3 KTL-L1
      - SUN2000 3.68 KTL-L1
      - SUN2000 4 KTL-L1
      - SUN2000 4.6 KTL-L1
      - SUN2000 5 KTL-L1
      - SUN2000 6 KTL-L1
  inverter_1_3phase_m1_models:
    name: "Inverter #1 3phase M1 Models"
    options:
      - Select
      - SUN2000 3 KTL-M1
      - SUN2000 4 KTL-M1
      - SUN2000 5 KTL-M1
      - SUN2000 6 KTL-M1
      - SUN2000 8 KTL-M1
      - SUN2000 10 KTL-M1
  inverter_1_3phase_map0_models:
    name: "Inverter #1 3phase MAP0 Models"
    options:
      - Select
      - SUN2000 5 KTL-MAP0
      - SUN2000 6 KTL-MAP0
      - SUN2000 8 KTL-MAP0
      - SUN2000 10 KTL-MAP0
      - SUN2000 12 KTL-MAP0
  # -----------------
  # Inverter #2 Setup
  inverter_2_1phase_l1_models:
    name: "Inverter #2 1phase L1 Models"
    options:
      - Select
      - SUN2000 2 KTL-L1
      - SUN2000 3 KTL-L1
      - SUN2000 3.68 KTL-L1
      - SUN2000 4 KTL-L1
      - SUN2000 4.6 KTL-L1
      - SUN2000 5 KTL-L1
      - SUN2000 6 KTL-L1
  inverter_2_3phase_m1_models:
    name: "Inverter #2 3phase M1 Models"
    options:
      - Select
      - SUN2000 3 KTL-M1
      - SUN2000 4 KTL-M1
      - SUN2000 5 KTL-M1
      - SUN2000 6 KTL-M1
      - SUN2000 8 KTL-M1
      - SUN2000 10 KTL-M1
  inverter_2_3phase_map0_models:
    name: "Inverter #2 3phase MAP0 Models"
    options:
      - Select
      - SUN2000 5 KTL-MAP0
      - SUN2000 6 KTL-MAP0
      - SUN2000 8 KTL-MAP0
      - SUN2000 10 KTL-MAP0
      - SUN2000 12 KTL-MAP0
# ----------
# INPUT TEXT
# ----------
input_text:
  ## ------------------
  ## Electricity Prices
  electricity_price_import:
    name: "Electricity Price Import (Energi Data Service by Default)"
  electricity_price_export:
    name: "Electricity Price Export (Energi Data Service - Sale by Default)"
# ---------------
# TEMPLATE SENSOR
# ---------------
template:
  - sensor:
      ## --------------------------------------
      ## Electricity Price for Energy Dashboard
      - name: "Energi Data Service - Negative"
        unique_id: energi_data_service_negative
        unit_of_measurement: DKK/kWh
        state: >
          {{ states('sensor.energi_data_service') | float(0) * (-1) }}
      ## ----------------------------
      ## Tariff on Electricity Export
      - name: "Tariff Export"
        unique_id: tariff_export
        unit_of_measurement: DKK/kWh
        state: >
          {% set energinet_indfoedningstarif = 0.3 %}
          {% set energinet_balancetarif = 0.24 %}
          {% set konstant_indfoedningstarif = 0.5 %}
          {% set jyskenergi_balancetarif = 2.5 %}
            {{ (
            energinet_indfoedningstarif + 
            energinet_balancetarif + 
            konstant_indfoedningstarif + 
            jyskenergi_balancetarif 
            ) / 100 }}
      ## --------------------
      ## Inverter Rated Power
      - name: "Inverter #1 Rated Power"
        unique_id: inverter_1_rated_power
        unit_of_measurement: W
        state: >
          {% if is_state('input_select.inverter_1_model','1phase L1') %}
            {% if is_state('input_select.inverter_1_1phase_l1_models','SUN2000 2 KTL-L1') %}
              {{ 2000 }}
            {% elif is_state('input_select.inverter_1_1phase_l1_models','SUN2000 3 KTL-L1') %}
              {{ 3000 }}
            {% elif is_state('input_select.inverter_1_1phase_l1_models','SUN2000 3.68 KTL-L1') %}
              {{ 3680 }}
            {% elif is_state('input_select.inverter_1_1phase_l1_models','SUN2000 4 KTL-L1') %}
              {{ 4000 }}
            {% elif is_state('input_select.inverter_1_1phase_l1_models','SUN2000 4.6 KTL-L1') %}
              {{ 4600 }}
            {% elif is_state('input_select.inverter_1_1phase_l1_models','SUN2000 5 KTL-L1') %}
              {{ 5000 }}
            {% elif is_state('input_select.inverter_1_1phase_l1_models','SUN2000 6 KTL-L1') %}
              {{ 6000 }}
            {% endif %}
          {% elif is_state('input_select.inverter_1_model','3phase M1') %}
            {% if is_state('input_select.inverter_1_3phase_m1_models','SUN2000 3 KTL-M1') %}
              {{ 3000 }}
            {% elif is_state('input_select.inverter_1_3phase_m1_models','SUN2000 4 KTL-M1') %}
              {{ 4000 }}
            {% elif is_state('input_select.inverter_1_3phase_m1_models','SUN2000 5 KTL-M1') %}
              {{ 5000 }}
            {% elif is_state('input_select.inverter_1_3phase_m1_models','SUN2000 6 KTL-M1') %}
              {{ 6000 }}
            {% elif is_state('input_select.inverter_1_3phase_m1_models','SUN2000 8 KTL-M1') %}
              {{ 8000 }}
            {% elif is_state('input_select.inverter_1_3phase_m1_models','SUN2000 10 KTL-M1') %}
              {{ 10000 }}
            {% endif %}
          {% elif is_state('input_select.inverter_1_model','3phase MAP0') %}
            {% elif is_state('input_select.inverter_1_3phase_map0_models','SUN2000 5 KTL-MAP0') %}
              {{ 5000 }}
            {% elif is_state('input_select.inverter_1_3phase_map0_models','SUN2000 6 KTL-MAP0') %}
              {{ 6000 }}
            {% elif is_state('input_select.inverter_1_3phase_map0_models','SUN2000 8 KTL-MAP0') %}
              {{ 8000 }}
            {% elif is_state('input_select.inverter_1_3phase_map0_models','SUN2000 10 KTL-MAP0') %}
              {{ 10000 }}
            {% elif is_state('input_select.inverter_1_3phase_map0_models','SUN2000 12 KTL-MAP0') %}
              {{ 12000 }}
            {% endif %}
          {% else %}
            {{ 0 }}
          {% endif %}
      - name: "Inverter #2 Rated Power"
        unique_id: inverter_2_rated_power
        unit_of_measurement: W
        state: >
          {% if is_state('input_select.inverter_2_model','1phase L1') %}
            {% if is_state('input_select.inverter_2_1phase_l1_models','SUN2000 2 KTL-L1') %}
              {{ 2000 }}
            {% elif is_state('input_select.inverter_2_1phase_l1_models','SUN2000 3 KTL-L1') %}
              {{ 3000 }}
            {% elif is_state('input_select.inverter_2_1phase_l1_models','SUN2000 3.68 KTL-L1') %}
              {{ 3680 }}
            {% elif is_state('input_select.inverter_2_1phase_l1_models','SUN2000 4 KTL-L1') %}
              {{ 4000 }}
            {% elif is_state('input_select.inverter_2_1phase_l1_models','SUN2000 4.6 KTL-L1') %}
              {{ 4600 }}
            {% elif is_state('input_select.inverter_2_1phase_l1_models','SUN2000 5 KTL-L1') %}
              {{ 5000 }}
            {% elif is_state('input_select.inverter_2_1phase_l1_models','SUN2000 6 KTL-L1') %}
              {{ 6000 }}
            {% endif %}
          {% elif is_state('input_select.inverter_2_model','3phase M1') %}
            {% if is_state('input_select.inverter_2_3phase_m1_models','SUN2000 3 KTL-M1') %}
              {{ 3000 }}
            {% elif is_state('input_select.inverter_2_3phase_m1_models','SUN2000 4 KTL-M1') %}
              {{ 4000 }}
            {% elif is_state('input_select.inverter_2_3phase_m1_models','SUN2000 5 KTL-M1') %}
              {{ 5000 }}
            {% elif is_state('input_select.inverter_2_3phase_m1_models','SUN2000 6 KTL-M1') %}
              {{ 6000 }}
            {% elif is_state('input_select.inverter_2_3phase_m1_models','SUN2000 8 KTL-M1') %}
              {{ 8000 }}
            {% elif is_state('input_select.inverter_2_3phase_m1_models','SUN2000 10 KTL-M1') %}
              {{ 10000 }}
          {% elif is_state('input_select.inverter_2_model','3phase MAP0') %}
            {% elif is_state('input_select.inverter_2_3phase_map0_models','SUN2000 5 KTL-MAP0') %}
              {{ 5000 }}
            {% elif is_state('input_select.inverter_2_3phase_map0_models','SUN2000 6 KTL-MAP0') %}
              {{ 6000 }}
            {% elif is_state('input_select.inverter_2_3phase_map0_models','SUN2000 8 KTL-MAP0') %}
              {{ 8000 }}
            {% elif is_state('input_select.inverter_2_3phase_map0_models','SUN2000 10 KTL-MAP0') %}
              {{ 10000 }}
            {% elif is_state('input_select.inverter_2_3phase_map0_models','SUN2000 12 KTL-MAP0') %}
              {{ 12000 }}
            {% endif %}
          {% else %}
            {{ 0 }}
          {% endif %}
